// Auto-generated by scripts/generate-blurhashes.cjs — do not edit manually.
// Re-run after adding or replacing assets:
//   node scripts/generate-blurhashes.cjs

export const blurhashes: Record<string, string> = {
  "locket/01-friendcircle": "L15}BMtR02VsK8NeIprpTKog~ARi",
  "locket/02-liveactivity": "LNN[{d?]kXRQIp~BJVxY00nQxuNH",
  "locket/03-share": "L3BpFP_1001I8=i{-nVM00Iu~q?P",
  "locket/04-friendrequest": "L89i#Hay58j[0UayxYa#}kayxuay",
  "locket/05-tagging": "L4BC}bNc00-m~qV@IoRk00jF~AIq",
  "locket/06-friendpermission": "LE9P$Ef6IpfQ0iayxZa|}layW=jt",
  "fetii/01-home": "LF9aI4M#J^t6%5RQxJs;x4aNSuoK",
  "fetii/02-ridenow": "LF7nL*xHaxacntkFaJaeXDV?flj=",
  "fetii/03-route": "LO9jHkoLNXa}Okjsogj]#_jbf5a{",
  "fetii/04-connecting": "L5BMfpRA9Dt70uxZo|bd0Ft6$-WB",
  "fetii/05-arrival": "LN9Zy~sqR~W-J{afjdfk#xofaxf8",
  "fetii/06-review": "LW9G0Po3Ria}S5fOo4f8#_jbbEfQ",
  "fetii/07-refer": "LZBN53n9Inae-aXNIBj]xxj[WBj[",
  "fetii/08-liveactivity": "LABfufNNnhNWNA?KM_n:00$%tAM{",
  "doordash/01-welcome": "L1RC#qtHLzpZ00pr8^9?005:00JN",
  "doordash/02-cards": "L3R3Zj009Y_300*JS^9F00?X00E2",
  "doordash/03-merchant-scroll": "L8RyZ]0000M{8vS4a0t8..?vt,x]",
  "doordash/04-check-in": "L2R3A,0eUa%#00+^}FZ$00?vYPS2",
  "doordash/05-merchant": "L1P?jy0000AM00RO4T0100?c0K00",
  "dive-chat/01-index": "L6Q]$p4mQ,ac00_4%2ozIoTdNGSK",
  "dive-chat/02-event": "LYG]8Nj[9Gj[_4oLRPfkrxofkUae",
  "dive-chat/03-chat": "L69Z=tK100=zyX$*IoNt4TRl~XRP",
  "dive-chat/04-calendar": "LoPsn#t8t7j?_NV@WBj]MwofkCay",
  "dive-chat/05-share": "L39QdQpw00tc?wR5DOVe57-B%MNL",
  "dive-chat/06-poll": "L1Rp2q8wxu%}00DOv#OB00l.pHMe",
  "dive-chat/07-search": "LcPGsy%1aKbvtQt8s.bb~WRjW?sl",
  "dive-chat/08-settings": "L2SPU:008w-Bxu-;%3of^Q^6vgv~"
}
